# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.26.4'

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
#array.nbytes

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
null_vector = np.zeros(10, dtype='int')
null_vector[4] = 1
null_vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
# Using the vector above
reversed_vector = vector[::-1]
reversed_vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
matrix = np.arange(0,9).reshape((3,3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
x = np.array([1,2,0,0,4,0])
np.nonzero(x)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
y = np.eye(3, dtype='int')
y

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
z = np.random.rand(3,3,3)
z

array([[[0.02051461, 0.87246718, 0.68488928],
        [0.52031135, 0.23024698, 0.44837655],
        [0.44172986, 0.21217089, 0.91714063]],

       [[0.96637978, 0.82215901, 0.67384827],
        [0.87612855, 0.68293105, 0.76933721],
        [0.61851039, 0.04513181, 0.46030538]],

       [[0.42504591, 0.51796772, 0.4590188 ],
        [0.81350951, 0.18102581, 0.70738164],
        [0.64591595, 0.10856544, 0.25487045]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
a = np.random.rand(10,10)
print(a)
print(a.max())
print(a.min())

[[0.69614169 0.57357267 0.58466981 0.23837705 0.2726441  0.40066814
  0.76612873 0.80041809 0.18805123 0.84107459]
 [0.12624853 0.65268042 0.15145913 0.78932888 0.39398283 0.70580952
  0.19195972 0.74195582 0.44414439 0.819177  ]
 [0.22348034 0.89483119 0.87133614 0.02062786 0.89713571 0.65950231
  0.51424413 0.87796163 0.28440996 0.68664502]
 [0.30546223 0.21907255 0.93733066 0.27707849 0.65852053 0.22457311
  0.67305558 0.12569421 0.41787194 0.60340432]
 [0.95932992 0.90410865 0.54209894 0.09897246 0.6173773  0.3219478
  0.69369573 0.92917646 0.23937355 0.57654774]
 [0.35978681 0.75253186 0.35696673 0.5778612  0.37983095 0.2586616
  0.3250299  0.71666822 0.25006852 0.47246964]
 [0.08423024 0.18449887 0.25529388 0.77221852 0.79516462 0.08269453
  0.27159834 0.47223622 0.37151672 0.8477237 ]
 [0.27918213 0.61341411 0.33442906 0.58892897 0.31475362 0.8452135
  0.61922787 0.6274128  0.60873466 0.10857812]
 [0.18873275 0.38184713 0.98706198 0.83078907 0.68451543 0.57158983
  0.39784516 0.

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [18]:
b = np.random.randint(100, size=30)
b.mean()

41.833333333333336

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [28]:
# Creating a 5 by 4 array
c = np.ones((5,4), dtype='int')
c[1:-1, 1:-1] = 0
c

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])